"""Reporting-layer contracts for the SSAT toolkit."""

from ssat.report.adapters import (
    ClassificationAdapter,
    DetectionAdapter,
    SampleMetricLike,
    TaskPresentationAdapter,
)
from ssat.report.assembler import AssembledReport, ReportDataAssembler
from ssat.report.charts import (
    RankCorrelationRowLike,
    render_fill_strategy_correlation,
    render_region_bar,
    render_vulnerability_histogram,
)
from ssat.report.errors import ReportDataError, ReportError, ReportSchemaError
from ssat.report.exporter import AssembledReportLike, ExportedPaths, export
from ssat.report.types import (
    FlaggedItem,
    GRADE_COLORS,
    MetricCard,
    ProvenanceInfo,
    REPORT_SCHEMA_VERSION,
    RegionRow,
    RegionSummary,
    ReliabilitySpotlight,
    ReportGrade,
    ReportJsonScalar,
    ReportJsonValue,
    ReportMeta,
    ReportModel,
    ReportSchemaVersions,
    RunSummary,
    SampleCard,
    SampleRankings,
    TaskKind,
    TopRegionEntry,
    VulnerabilityDistribution,
    VulnerabilitySummaryStats,
)

__all__ = [
    "AssembledReport",
    "AssembledReportLike",
    "ClassificationAdapter",
    "DetectionAdapter",
    "ExportedPaths",
    "FlaggedItem",
    "GRADE_COLORS",
    "MetricCard",
    "ProvenanceInfo",
    "RankCorrelationRowLike",
    "REPORT_SCHEMA_VERSION",
    "RegionRow",
    "RegionSummary",
    "ReliabilitySpotlight",
    "ReportDataAssembler",
    "ReportDataError",
    "ReportError",
    "ReportGrade",
    "ReportJsonScalar",
    "ReportJsonValue",
    "ReportMeta",
    "ReportModel",
    "ReportSchemaError",
    "ReportSchemaVersions",
    "RunSummary",
    "SampleCard",
    "SampleMetricLike",
    "SampleRankings",
    "TaskKind",
    "TaskPresentationAdapter",
    "TopRegionEntry",
    "VulnerabilityDistribution",
    "VulnerabilitySummaryStats",
    "export",
    "render_fill_strategy_correlation",
    "render_region_bar",
    "render_vulnerability_histogram",
]
