"""Reporting-layer contracts for the SSAT toolkit."""

from ssat.report.errors import ReportDataError, ReportError, ReportSchemaError
from ssat.report.types import (
    FlaggedItem,
    MetricCard,
    ProvenanceInfo,
    REPORT_SCHEMA_VERSION,
    RegionRow,
    RegionSummary,
    ReliabilitySpotlight,
    ReportGrade,
    ReportJsonScalar,
    ReportJsonValue,
    ReportMeta,
    ReportModel,
    ReportSchemaVersions,
    RunSummary,
    SampleCard,
    SampleRankings,
    TaskKind,
    TopRegionEntry,
    VulnerabilityDistribution,
    VulnerabilitySummaryStats,
)

__all__ = [
    "FlaggedItem",
    "MetricCard",
    "ProvenanceInfo",
    "REPORT_SCHEMA_VERSION",
    "RegionRow",
    "RegionSummary",
    "ReliabilitySpotlight",
    "ReportDataError",
    "ReportError",
    "ReportGrade",
    "ReportJsonScalar",
    "ReportJsonValue",
    "ReportMeta",
    "ReportModel",
    "ReportSchemaError",
    "ReportSchemaVersions",
    "RunSummary",
    "SampleCard",
    "SampleRankings",
    "TaskKind",
    "TopRegionEntry",
    "VulnerabilityDistribution",
    "VulnerabilitySummaryStats",
]
