"""UI-independent application facade for SSAT."""

from ssat.application.application import AuditApplication, PreparedRun
from ssat.application.types import (
    AnalyzeRequest,
    AnalyzeResult,
    ApplicationError,
    ApplicationErrorCode,
    ApplicationEvent,
    CancellationToken,
    ComputeMetricsRequest,
    ComputeMetricsResult,
    DumpSectionSummary,
    DumpSummary,
    EstimateRequest,
    EstimateResult,
    EventSink,
    ExportLabelsRequest,
    ExportLabelsResult,
    IndexRebuildResult,
    InspectRequest,
    RebuildIndexRequest,
    ReportRequest,
    ReportResult,
    RunRequest,
    RunResult,
)

__all__ = [
    "AnalyzeRequest",
    "AnalyzeResult",
    "ApplicationError",
    "ApplicationErrorCode",
    "ApplicationEvent",
    "AuditApplication",
    "CancellationToken",
    "ComputeMetricsRequest",
    "ComputeMetricsResult",
    "DumpSectionSummary",
    "DumpSummary",
    "EstimateRequest",
    "EstimateResult",
    "EventSink",
    "ExportLabelsRequest",
    "ExportLabelsResult",
    "IndexRebuildResult",
    "InspectRequest",
    "PreparedRun",
    "RebuildIndexRequest",
    "ReportRequest",
    "ReportResult",
    "RunRequest",
    "RunResult",
]
